### ISSUE TITLE
Register in website 

### ISSUE THREAD

**Issue by leontino** [tolgatasci/whatsapp-api-python#1]
Hi. First congratulations for this project. Second, I don't receive the confirmation code from website. My number is from Brazil.

**Comment by tolgatasci** [comment]
please again register. I created a server in my own home as a server because I did not have a budget. However, since there is a power outage, Laravel job stopped because I did not start it.

**Comment by tolgatasci** [comment]
![image](https://user-images.githubusercontent.com/9893685/113504585-b2328400-9541-11eb-8c5b-92a74c403dfc.png)

We send code but you not register whatsapp ?

**Comment by tolgatasci** [comment]
![image](https://user-images.githubusercontent.com/9893685/113504608-e148f580-9541-11eb-95a9-d0c736f1f912.png)

We send code but you not register whatsapp ?

**Comment by leontino** [comment]
I'm not receiving yet message confirmation code in whatsapp.

Em dom., 4 de abr. de 2021 06:33, Tolga ***@***.***> escreveu:

**Comment by tolgatasci** [comment]
+55*******02913
your number it is true ?

**Comment by tolgatasci** [comment]
all right. this is a bug. I started working for the solution.

**Comment by tolgatasci** [comment]
558599402913@s.whatsapp.net working 

5585999402913
5585999402913@s.whatsapp.net not working

your enter number error because one 9 number much
